-- Event table: Stores event information
CREATE TABLE EVENT (
  EVENT_ID INT PRIMARY KEY,
  EVENT_NAME VARCHAR(255),
  EVENT_DATE DATETIME
);

-- Attendee table: Stores attendee's information
CREATE TABLE ATTENDEE (
  ATTENDEE_ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  NUMBER VARCHAR(15),
  EVENT_ID INT,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

-- Venue table: Contains venue data for events
CREATE TABLE VENUE (
  VENUE_ID INT PRIMARY KEY,
  VENUE_NAME VARCHAR(255),
  CAPACITY INT
);

-- Vendor table: Provides goods/services for events
CREATE TABLE VENDOR (
  VENDOR_ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  AVAILABILITY VARCHAR(255) -- Alternate: JSON or DATETIME fields
);

-- Task table: Different event-related tasks
CREATE TABLE TASK (
  TASK_ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  EVENT_ID INT,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

-- Schedule table: Event schedules/timings
CREATE TABLE SCHEDULE (
  SCHEDULE_ID INT PRIMARY KEY,
  EVENT_ID INT,
  START_DATE DATETIME,
  END_TIME DATETIME,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

-- Budget table: Event budgets
CREATE TABLE BUDGET (
  BUDGET_ID INT PRIMARY KEY,
  EVENT_ID INT,
  TOTAL_BUDGET DECIMAL(10,2),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
